services:
  - type: web
    name: my-store
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn store.wsgi:application"
    pythonVersion: 3.11.9
